version: '3'

services:
  frontend:
    build:
      context: ./chatapp
    ports:
      - "3000:3000"
    env_file:
      - .env

  backend:
    build:
      context: ./chat-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
